

FROM centos:6

MAINTAINER Bharani Chennu bchennu@cisco.com

ENV JAVA_VERSION 8u31
ENV BUILD_VERSION b13

RUN yum -y update

RUN yum install -y tar

RUN yum -y install wget
# Downloading Java
RUN wget --no-cookies --no-check-certificate --header "Cookie: oraclelicense=accept-securebackup-cookie" "http://download.oracle.com/otn-pub/java/jdk/$JAVA_VERSION-$BUILD_VERSION/jdk-$JAVA_VERSION-linux-x64.rpm" -O /tmp/jdk-8-linux-x64.rpm

RUN yum -y install /tmp/jdk-8-linux-x64.rpm

RUN alternatives --install /usr/bin/java jar /usr/java/latest/bin/java 200000
RUN alternatives --install /usr/bin/javaws javaws /usr/java/latest/bin/javaws 200000
RUN alternatives --install /usr/bin/javac javac /usr/java/latest/bin/javac 200000

ENV JAVA_HOME /usr/java/latest

#setting up maven


RUN wget http://repos.fedorapeople.org/repos/dchen/apache-maven/epel-apache-maven.repo -O /etc/yum.repos.d/epel-apache-maven.repo

RUN yum install -y apache-maven



ENV M2_HOME /usr/share/apache-maven
ENV M2 $M2_HOME/bin
ENV PATH $M2:$PATH

RUN yum -y install git

RUN yum install -y firefox

RUN yum install -y dbus


RUN wget www.eclipse.org/downloads/download.php?file=/technology/epp/downloads/release/kepler/R/eclipse-jee-kepler-R-linux-gtk-x86_64.tar.gz -O eclipse.tar.gz

RUN mv eclipse.tar.gz /opt/

WORKDIR /opt

RUN tar xvf eclipse.tar.gz

RUN ln -s /opt/eclipse/eclipse /usr/local/bin/eclipse



# Replace 0 with your user / group id
RUN export uid=1000 gid=1000
RUN mkdir -p /home/developer
RUN echo "developer:x:${uid}:${gid}:Developer,,,:/home/developer:/bin/bash" >> /etc/passwd
RUN echo "developer:x:${uid}:" >> /etc/group
RUN echo "developer ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
RUN chmod 0440 /etc/sudoers
RUN chown ${uid}:${gid} -R /home/developer

RUN dbus-uuidgen > /etc/machine-id

RUN dbus-uuidgen >> /var/lib/dbus/machine-id


USER developer
ENV HOME /home/developer


RUN yum -y install wget gcc gcc-c++ make
RUN wget http://people.centos.org/tru/devtools-2/devtools-2.repo -O /etc/yum.repos.d/devtools-2.repo
RUN yum install -y devtoolset-2-gcc devtoolset-2-binutils devtoolset-2-gcc-c++
RUN ln -s /opt/rh/devtoolset-2/root/usr/bin/* /usr/local/bin/


